// Clases de tailwind con los que tuve problemas y opté por esta solución

export const titleLine = "w-screen relative z-10 flex items-center justify-center text-center before:border-t-2 before:border-current before:mx-auto before:absolute before:top-1/2 before:left-0 before:right-0 before:bottom-0 before:w-full before:-z-10 before:hidden before:md:flex"

export const inputClass = "peer w-full h-full bg-transparent text-blue-gray-700 font-sans font-normal outline outline-0 focus:outline-0 disabled:bg-blue-gray-50 disabled:border-0 transition-all placeholder-shown:border placeholder-shown:border-t placeholder-shown:border-t-blue-gray-200 border focus:border-t-transparent text-sm px-3 py-2.5 rounded-[7px] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none bg-white";

export const labelClass = "flex w-full h-full select-none pointer-events-none absolute left-0 font-normal !overflow-visible truncate peer-placeholder-shown:text-blue-gray-500 leading-[1.75] peer-focus:leading-[1.75] peer-disabled:text-transparent peer-disabled:peer-placeholder-shown:text-blue-gray-500 transition-all -top-1.5 peer-placeholder-shown:text-sm text-[11px] peer-focus:text-[11px] before:content[' '] before:block before:box-border before:w-2.5 before:h-1.5 before:mt-[6.5px] before:mr-1 before:pointer-events-none before:transition-all peer-disabled:before:pointer-events-none after:content[' '] after:block after:flex-grow after:box-border after:w-2.5 after:h-1.5 after:mt-[6.5px] after:ml-1 after:pointer-events-none after:transition-all peer-disabled:after:pointer-events-none peer-placeholder-shown:leading-[3.75] text-gray-500 peer-focus:text-gray-900 peer-focus:before:!border-gray-900";

export const checkboxClass = "before:content[''] peer relative h-5 w-5 cursor-pointer appearance-none rounded-md border border-blue-gray-200 transition-all before:absolute before:top-2/4 before:left-2/4 before:block before:h-12 before:w-12 before:-translate-y-2/4 before:-translate-x-2/4 before:rounded-full before:opacity-0 before:transition-opacity checked:before:border-transparent checked:before:bg-transparent checked:border-transparent checked:bg-transparent hover:before:opacity-10";
